# Hack to avoid conflicts with workspaces
[workspace]

[package]
name = "mia"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mia"
path = "mia.rs"

[dependencies]
nix = { version = "0.29", features = ["mount", "reboot"] }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"
