[workspace]
resolver = "2"

members = [
  "mia-installer",
]

[workspace.package]
authors = ["Gevulot Team"]
edition = "2021"
repository = "https://github.com/gevulotnetwork/mia"

[workspace.dependencies]
# TODO: replace rev with tag when possible
gevulot-rs = { git = "https://github.com/gevulotnetwork/gevulot-rs.git", rev = "f6657f57771b1c549a83cfe6fc822c3db687707e" }

anyhow = "1"
env_logger = "0.11.5"
log = "0.4.22"
serde = "1"
serde_yaml = "0.9.34"
structopt = "0.3.26"
fs_extra = "1"
