[workspace]
resolver = "2"

members = [
  "mia-installer",
  "mia-rt-config",
]

[workspace.package]
authors = ["Gevulot Team"]
edition = "2021"
repository = "https://github.com/gevulotnetwork/mia"

[workspace.dependencies]
mia-rt-config = { path = "mia-rt-config" }
anyhow = "1"
env_logger = "0.11.5"
log = "0.4.22"
serde = "1"
serde_yaml = "0.9.34"
structopt = "0.3.26"
fs_extra = "1"
