# NOTE: hack to avoid workspace conflicts when building mia
[workspace]

[package]
name = "mia"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mia"
path = "src/mia.rs"

[dependencies]
nix = { version = "0.29", features = ["mount", "reboot"] }
mia-rt-config = { path = "../mia-rt-config" }
clap = { version = "4.5", features = ["derive"] }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"
