# NOTE: hack to avoid workspace conflicts when building mia
[workspace]

[package]
name = "mia"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "mia"
path = "src/mia.rs"

[dependencies]
mia-rt-config = { path = "../mia-rt-config" }
env_logger = "0.11.5"
log = "0.4.22"
serde_yaml = "0.9.34"
nix = { version = "0.29", features = ["mount", "reboot"] }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"
