name: Run all tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install buf
        uses: bufbuild/buf-setup-action@v1
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test
      - name: Run test MIA installation
        run: |
          mkdir tmp
          RUST_LOG=mia_installer=debug cargo run -- --prefix ./tmp --platform x86_64-unknown-linux-gnu
      - name: Run MIA in chroot
        run: |
          sudo chroot ./tmp /usr/lib/mia/mia
